accounts/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from jobsapp.views import EditProfileView
from .views import *

app_name = "accounts"

urlpatterns = [
    path('employee/register', RegisterEmployeeView.as_view(), name='employee-register'),
    path('employer/register', RegisterEmployerView.as_view(), name='employer-register'),
    path('employee/profile/update', EditProfileView.as_view(), name='employer-profile-update'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('login', LoginView.as_view(), name='login'),
    path('contact', contactview, name='contact'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
    path('info',include('resumesite.urls'))
]

jobsapp/urls.py
from django.urls import path, include

from .views import *

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    # path('contact',contactview.as_view(),name='contactview'),
    # path('about',aboutview.as_view(),name='aboutview'),
]

resumesite/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('resume/', views.home, name="home"),
    path('',views.info,name="info")
]

resumesite/models.py
from django.db import models

# Create your models here.

resumesite/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,Submit
from crispy_forms.layout import Column
from crispy_forms.layout import Row


# class SkillWidget(forms.MultiWidget):
# 	def __init__(self,attrs=None):
# 		super().__init__([
# 			forms.TextInput(),
# 			forms.TextInput(),
# 			forms.TextInput(),
# 			forms.TextInput(),
# 			forms.TextInput(),
# 			forms.TextInput(),
# 			forms.TextInput(),
# 		],attrs)

# 	def decompress(self,value):
# 		if value:
# 			return value.split(' ')
# 		return(['','','','','','',''])

# class SkillsField(forms.MultiValueField):
# 	widget=SkillWidget
# 	def __init__(self,*args,**kwargs):
# 		fields=(forms.CharField(),
# 			forms.CharField(),
# 			forms.CharField(),
# 			forms.CharField(required=False),
# 			forms.CharField(required=False),
# 			forms.CharField(required=False),
# 			forms.CharField(required=False),
# 			)
# 		super().__init__(fields,*args,**kwargs)

# 	def compress(self,data_list):
# 		return f'{data_list[0]} {data_list[1]} {data_list[2]} {data_list[3]} {data_list[4]} {data_list[5]} {data_list[6]}'


# class ExpWidget(forms.MultiWidget):
# 	def __init__(self,attrs=None):
# 		super().__init__([
# 			forms.TextInput(),
# 			forms.TextInput(),
# 			forms.TextInput()#,
# 		],attrs)

# 	def decompress(self,value):
# 		if value:
# 			return value.split(' ')
# 		return(['','',''])

# class ExpField(forms.MultiValueField):
# 	widget=ExpWidget
# 	def __init__(self,*args,**kwargs):
# 		fields=(forms.CharField(),#validators can be added
# 			forms.CharField(),
# 			forms.CharField(),
# 			)
# 		super().__init__(fields,*args,**kwargs)

# 	def compress(self,data_list):
# 		return f'{data_list[0]} {data_list[1]} {data_list[2]}'

# class EduWidget(forms.MultiWidget):
# 	def __init__(self,attrs=None):
# 		super().__init__([
# 			forms.TextInput(),
# 			forms.TextInput(),
# 			forms.TextInput()#,
# 		],attrs)

# 	def decompress(self,value):
# 		if value:
# 			return value.split(' ')
# 		return(['','',''])

# class EduField(forms.MultiValueField):
# 	widget=EduWidget
# 	def __init__(self,*args,**kwargs):
# 		fields=(forms.CharField(),#validators can be added
# 			forms.CharField(),
# 			forms.CharField(),
# 			)
# 		super().__init__(fields,*args,**kwargs)

# 	def compress(self,data_list):
# 		return f'{data_list[0]} {data_list[1]} {data_list[2]}'


class ContactForm(forms.Form):
	name=forms.CharField()#required=False
	email=forms.EmailField(label='E-Mail')
	mobile=forms.CharField()
	address=forms.CharField()
	skills_1=forms.CharField()
	skills_2=forms.CharField()
	skills_3=forms.CharField(required=False)
	skills_4=forms.CharField(required=False)

	experience_1_title=forms.CharField()
	experience_1_dur=forms.CharField()
	experience_1_desc=forms.CharField()

	experience_2_title=forms.CharField(required=False)
	experience_2_dur=forms.CharField(required=False)
	experience_2_desc=forms.CharField(required=False)

	education_1=forms.CharField()
	education_1_dur=forms.CharField()
	education1_score=forms.CharField()

	education_2=forms.CharField()
	education_2_dur=forms.CharField()
	education2_score=forms.CharField()

	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		self.helper=FormHelper
		self.helper.form_class = ' container justify-content-center '
		# self.helper.label_class = ''
		# self.helper.field_class = 'col-md-6 col-xs-9'
		self.helper.form_method="post"
		self.helper.layout=Layout(
			Row(
                Column('name', css_class='form-group col-md-5  mb-10'),
                Column('email', css_class='form-group col-md-7 mb-10'),
                css_class='form-row  center'
            ),
			Row(
                Column('mobile', css_class='form-group col-md-5  mb-10'),
                Column('address', css_class='form-group col-md-7 mb-10'),
                css_class='form-row  center'
            ),
			Row(
                Column('skills_1', css_class='form-group col-md-6  mb-10'),
                Column('skills_2', css_class='form-group col-md-6 mb-10'),
                css_class='form-row  center'
            ),
			Row(
                Column('skills_3', css_class='form-group col-md-6  mb-10'),
                Column('skills_4', css_class='form-group col-md-6 mb-10'),
                css_class='form-row  center'
            ),
			Row(
                Column('experience_1_title', css_class='form-group col-md-7  mb-10'),
                Column('experience_1_dur', css_class='form-group col-md-5 mb-10'),
                css_class='form-row  center'
            ),
			'experience_1_desc',
			Row(
                Column('experience_2_title', css_class='form-group col-md-7  mb-10'),
                Column('experience_2_dur', css_class='form-group col-md-5 mb-10'),
                css_class='form-row  center'
            ),
			'experience_2_desc',
			'education_1',
			Row(
                Column('education_1_dur', css_class='form-group col-md-6 mb-10'),
                Column('education1_score', css_class='form-group col-md-6 mb-10'),
                css_class='form-row  center'
            ),
			'education_2',
			Row(
                Column('education_2_dur', css_class='form-group col-md-6  mb-10'),
                Column('education2_score', css_class='form-group col-md-6 mb-10'),
                css_class='form-row  center'
            ),
			Submit('submit','Submit',css_class="btn-success")
			)

resumesite/views.py
from django.shortcuts import render
from .forms import ContactForm

def home(request):
	return render(request, 'home.html', {})

def info(request):
	form=ContactForm()
	if request.method == 'POST':
		form=ContactForm(request.POST)
		if form.is_valid():
			name=form.cleaned_data['name']
			email=form.cleaned_data['email']

			skills_1=form.cleaned_data['skills_1']
			skills_2=form.cleaned_data['skills_2']
			skills_3=form.cleaned_data['skills_3']
			skills_4=form.cleaned_data['skills_4']

			mobile=form.cleaned_data['mobile']
			address=form.cleaned_data['address']

			experience_1_title=form.cleaned_data['experience_1_title']
			experience_1_dur=form.cleaned_data['experience_1_dur']
			experience_1_desc=form.cleaned_data['experience_1_desc']

			experience_2_title=form.cleaned_data['experience_2_title']
			experience_2_dur=form.cleaned_data['experience_2_dur']
			experience_2_desc=form.cleaned_data['experience_2_desc']

			education_1=form.cleaned_data['education_1']
			education_1_dur=form.cleaned_data['education_1_dur']
			education1_score=form.cleaned_data['education1_score']

			education_2=form.cleaned_data['education_2']
			education_2_dur=form.cleaned_data['education_2_dur']
			education2_score=form.cleaned_data['education2_score']

			data={'name':name}
			data['email']=email
			data['skills_1']=skills_1
			data['skills_2']=skills_2
			data['skills_3']=skills_3
			data['skills_4']=skills_4

			data['mobile']=mobile
			data['address']=address

			data['experience_1_title']=experience_1_title
			data['experience_1_dur']=experience_1_dur
			data['experience_1_desc']=experience_1_desc

			data['experience_2_title']=experience_2_title
			data['experience_2_dur']=experience_2_dur
			data['experience_2_desc']=experience_2_desc

			data['education_1']=education_1
			data['education_1_dur']=education_1_dur
			data['education1_score']=education1_score

			data['education_2']=education_2
			data['education_2_dur']=education_2_dur
			data['education2_score']=education2_score
			return render(request,'homeresume.html',data)
			#to add more go to : forms.py
			# print(name,email)
	return render(request,'info.html',{'form':form})

resumesite/templates/homeresume.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Sakshi-Aafiya-Hasti- Curriculum Vitae</title>
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="The Curriculum Vitae of Sakshi-Aafiya-Hasti Bloggs." />
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700|Lato:400,300' rel='stylesheet' type='text/css'>
   <!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body id="top">
    <div id="cv" class="instaFade">
        <div class="mainDetails">
            <div id="headshot" class="quickFade">
                <img src="{% static 'img/headshot.jpg' %}" alt="Alan Smith" />
            </div>



            <div id="name">

                <h1 class="quickFade delayTwo">{{ name }}</h1>

                <h2 class="quickFade delayThree">SOFTWARE DEVELOPER</h2>

            </div>



            <div id="contactDetails" class="quickFade delayFour">
                <ul>
                    <li>e: {{email}}</li>
                    <!-- <li>w: <a href="http://www.bloggs.com">www.bloggs.com</a></li>
 -->                    <li>m: {{mobile}}</li>
                </ul>
            </div>
            <div class="clear"></div>

        </div>


        <div id="mainArea" class="quickFade delayFive">
            <section>
                <article>
                    <div class="sectionTitle">
                        <h1>Personal Profile</h1>
                    </div>


                    <div class="sectionContent">
                        <p>Address: {{address}}
                        </p>
                    </div>

                </article>

                <div class="clear"></div>

            </section>


            <section>

                <div class="sectionTitle">

                    <h1>
                        Work Experience
                    </h1>

                </div>



                <div class="sectionContent">

                    <article>

                        <h2>{{experience_1_title}}</h2>
                        <p class="subDetails">{{experience_1_dur}}</p>
                        <p> {{experience_1_desc}}</p>
                    </article>



                    <article>

                        <h2>{{experience_2_title}}</h2>
                        <p class="subDetails">{{experience_2_dur}}</p>
                        <p> {{experience_2_desc}}</p>                   


                    </article>


                </div>

                <div class="clear"></div>

            </section>





            <section>

                <div class="sectionTitle">

                    <h1>Key Skills</h1>

                </div>



                <div class="sectionContent">

                    <ul class="keySkills">

                        <li>{{skills_1}}</li>
                        <li>{{skills_2}}</li>
                        <li>{{skills_3}}</li>
                        <li>{{skills_4}}</li>

                    </ul>

                </div>

                <div class="clear"></div>

            </section>





            <section>

                <div class="sectionTitle">

                    <h1>Education</h1>

                </div>



                <div class="sectionContent">

                    <article>

                        <h2>{{education_1}}</h2>

                        <p class="subDetails">{{education_1_dur}}</p>

                        <p>Score : {{education1_score}}</p>

                    </article>

                    <article>

                        <h2>{{education_2}}</h2>

                        <p class="subDetails">{{education_2_dur}}</p>

                        <p>Score : {{education2_score}}</p>

                    </article>

                </div>

                <div class="clear"></div>

            </section>



        </div>

    </div>

    <script type="text/javascript">
        var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");

        document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>

    <script type="text/javascript">
        var pageTracker = _gat._getTracker("UA-3753241-1");

        pageTracker._initData();

        pageTracker._trackPageview();
    </script>

</body>

</html>

resumesite/templates/info.html
{% load crispy_forms_tags %}{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Sakshi-Aafiya-Hasti Resume Builder</title>
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="The Curriculum Vitae of Sakshi-Aafiya-Hasti Bloggs." />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body style="padding:20px;">
    <!--<h1 class="mt-2" style="text-align:center;font-weight:bolder;color:steelblue;">Welcome to SAH Resume Builder!!!</h1>
    <hr class="mt-0 mb-4">-->
    <header class="header">
        <nav class="navbar navbar-expand-lg bg-dark">
            <div class="container">
                <a href="/" class="navbar-brand">
                    <img src="{% static 'img/itsourcecodes.jpg' %}" alt="logo" class="d-none d-lg-block">
                    <span class="sr-only">Home</span>
                </a>
                <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                        class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
                </button>
                <div id="navbarSupportedContent" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a href="/" class="nav-link">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a href="/info" class="nav-link">Build Resume <span class="sr-only">(current)</span></a>
                        </li>
                        <!-- <li class="nav-item">
                            <a href="#" class="nav-link">About Us</a>
                        </li> -->
                        <li class="nav-item">
                            <a href="contact" class="nav-link">Contact</a>
                        </li>
                        {% if request.user.is_authenticated and request.user.role == 'employer' %}
                            <li class="nav-item dropdown">
                                <a id="clientZone" href="#" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false"
                                   class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                    <div class="client-menu-image">
                                        <div class="inner">
                                            <img src="{% static 'img/itsourcecodes.jpg' %}"
                                                 alt="company image"
                                                 class="img-fluid">
                                        </div>
                                    </div>
                                    {% if request.user.role == 'employee' %}
                                        {{ request.user.first_name }} {{ request.user.last_name }}
                                    {% else %}
                                        {{ request.user.first_name }}
                                    {% endif %}
                                </a>
                                <div aria-labelledby="clientZone" class="dropdown-menu">
                                    <a href="{% url 'jobs:employer-dashboard' %}" class="dropdown-item">Dashboard</a>
                                    <a href="{% url 'jobs:employer-all-applicants' %}" class="dropdown-item">Applicants </a>
                                    <a href="{% url 'jobs:employer-jobs-create' %}" class="dropdown-item">Post a new
                                        job </a>
                                    <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                                </div>
                            </li>
                        {% elif request.user.is_authenticated and request.user.role == 'employee' %}
                            <li class="nav-item dropdown">
                                <a id="clientZone" href="#" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false"
                                   class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                    <div class="client-menu-image">
                                        <div class="inner">
                                            <img src="{% static 'img/itsourcecodes.jpg' %}"
                                                 alt="company image"
                                                 class="img-fluid">
                                        </div>
                                    </div>
                                    {% if request.user.role == 'employee' %}
                                        {{ request.user.first_name }} {{ request.user.last_name }}
                                    {% else %}
                                        {{ request.user.first_name }}
                                    {% endif %}
                                </a>
                                <div aria-labelledby="clientZone" class="dropdown-menu">
                                    <a href="{% url 'accounts:employer-profile-update' %}" class="dropdown-item">Edit Profile</a>
                                    <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                                </div>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown">
                                <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                   class="nav-link dropdown-toggle"><i class="fa fa-signing"></i>Register
                                </a>
                                <div aria-labelledby="pages" class="dropdown-menu">
                                    <a href="{% url 'accounts:employee-register' %}" class="dropdown-item">Employee</a>
                                    <a href="{% url 'accounts:employer-register' %}" class="dropdown-item">Employers</a>
                                </div>
                            </li>
                            <li class="nav-item" style="color: #fff">
                                <a href="{% url 'accounts:login' %}" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                    <i class="fa fa-sign-in"></i>Login
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <h1 class="mt-2" style="text-align:center;font-weight:bolder;color:steelblue;">Welcome to SAH Resume Builder!!!</h1>
    <hr class="mt-0 mb-4">
<!--     <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='Submit'>Submit</button>
        
    </form> -->
    {% crispy form form.helper %}
    <footer class="footer">
        <div class="footer__block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-12 mb-5">
                        <h4 class="h5">About Jobs</h4>
                        <p> A job, employment, work or occupation, is a person's role in society. More specifically, a job is an activity, often regular and often performed in exchange for payment. Many people have multiple jobs. A person can begin a job by becoming an employee, volunteering, starting a business, or becoming a parent. </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer__copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-md-left text-center">
                        <p>Online Itsourcecode Portal Jobs System 2021</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>