jobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
    path('info',include('resumesite.urls'))
]

jobsapp/urls.py
from django.urls import path, include

from .views import *

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    # path('contact',contactview.as_view(),name='contactview'),
    # path('about',aboutview.as_view(),name='aboutview'),
]

templates/jobs/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Add a new position</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    <strong>{{ field.name }} {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                    <form id="job-main-form" method="post" action="" class="job-add-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12">
                                <h4>Job details</h4>
                                <p class="text-muted text-small">Code and test programming for software and mobile apps and etc. Develop and deploy computer applications. Execute code builds to test and production environments. Fix bugs in existing code.</p>
                                <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="title">Job Title</label>
                                <input id="title" name="title" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="text">Job Description</label>
                                <textarea id="text" name="description" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="location">Location</label>
                                <input id="location" name="location" type="text" placeholder="e.g. Rio de Janeiro"
                                       class="form-control">
                            </div>
                            <div class="col-lg-6 form-group">
                                <label for="type">Type</label>
                                <select id="type" name="type" placeholder="Choose job type"
                                        class="form-control select2">
                                    <option value="1">Full time</option>
                                    <option value="2">Part time</option>
                                    <option value="3">Internship</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="category">Category</label>
                                <select id="category" name="category" placeholder="Choose category"
                                        class="form-control select2">
                                    <option value="web-design">Web design</option>
                                    <option value="graphic-design">Graphic design</option>
                                    <option value="web-development">Web development</option>
                                    <option value="human-resource">Human Resources</option>
                                    <option value="support">Support</option>
                                    <option value="android">Android</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6 form-group">
                                <label for="apply_url">Apply URL <span
                                        class="note">(users will apply on your website)</span></label>
                                <input id="apply_url" type="url" class="form-control">
                            </div>
                            <div class="col-xl-6 form-group">
                                <label for="validity">Validity of the post</label>
                                <input id="validity" name="last_date" type="date" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <hr class="margin-bottom--big">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <h4>Company details</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="company_name">Company name</label>
                                <input id="company_name" name="company_name" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="company_description">Company Description</label>
                                <textarea id="company_description" name="company_description" rows="3"
                                          class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4 form-group">
                                <label for="company_website">Website</label>
                                <input id="company_website" name="website" type="url" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <hr>
                                <div class="checkbox text-center">
                                    <label>
                                        <input type="checkbox"> I agree with the <a href="#">Terms and conditions</a>.
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 text-center">
                                <hr>
                                <button type="submit" class="btn btn-success"><i class="fa fa-magic"></i>
                                    Save and publish
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/details.html
{% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}
{% block title %}
    Job details
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <h1 class="heading">{{ job.title }}<br>
                <small>at <a href="#"> {{ job.company_name }}</a></small>
            </h1>
            <div class="job-detail-description"><i class="fa fa-map-marker job__location"> </i>
                {{ job.location }} | Posted {{ job.created_at|timesince }} |
                {% if job.type == '1' %}
                    <span class="badge featured-badge badge-success">Full time</span>
                {% elif job.type == '2' %}
                    <span class="badge featured-badge badge-primary">Part time</span>
                {% else %}
                    <span style="color: #ffffff;" class="badge featured-badge badge-warning">Internship</span>
                {% endif %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Category: {{ job.category }}</h3>
                    <h5>Last date: {{ job.last_date|date }}</h5>
                    <h5 class="text-info">Salary: Negotiable</h5>
                    <blockquote class="blockquote">
                        <p>{{ job.description }}</p>
                    </blockquote>
                    <div class="job-detail__apply-bottom">
                        {% if request.user.is_authenticated %}
                            {% is_already_applied job request.user as is_applied %}
                            {% if is_applied %}
                                <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                            {% else %}
                                <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="job" value="{{ job.id }}">
                                    <input type="submit" class="btn btn-success"
                                           value="Apply for this job"/>
                                </form>
                            {% endif %}
                        {% else %}
                            <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="job" value="{{ job.id }}">
                                <input type="submit" class="btn btn-success"
                                       value="Apply for this job"/>
                            </form>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-3">
                    <h4>About {{ job.company_name }}</h4>
                    <p class="job-detail__company-description">{{ job.company_description }}</p>
                    <p class="job-detail__social social social--outline">
                        <a href="{{ job.website }}" data-toggle="tooltip" data-placement="top" title="Website"
                           class="link">
                            <i class="fa fa-link"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter" class="twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook" class="facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                    <div class="job-detail__apply-top">
                        {% if is_applied %}
                            <input type="button" class="btn btn-outline-white-primary" value="Already applied"/>
                        {% else %}
                            <form action="{% url 'jobs:apply-job' job.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="job" value="{{ job.id }}">
                                <input type="submit" class="btn btn-success" value="Apply for this job"/>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/jobs.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All jobs
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <h4 class="heading">Find a <span class="accent">job </span> that will <span class="accent">fit to your experties</span></h4>
            <form id="job-main-form" method="get" action="#" class="job-main-form">
                <div class="controls">
                    <div class="row align-items-end">
                        <div class="col-sm-1 col-lg-2"></div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="profession">Profession</label>
                            <input type="text" id="profession" name="profession"
                                   placeholder="Profession you are looking for" class="form-control">
                        </div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="location">Location</label>
                            <input type="text" id="location" name="location" placeholder="Any particular location?"
                                   value="Bay Area" class="form-control">
                        </div>
                        <div class="col-sm-1 col-lg-2 form-group">
                            <button type="submit" name="name"
                                    class="btn btn-outline-white-primary job-main-form__button">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ jobs.count }}</span> jobs</h3>
            {% for job in jobs %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title"><a
                                            href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h4>
                                    <p class="job__company">
                                        {{ job.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ job.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ job.created_at|timesince }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

templates/jobs/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All jobs
{% endblock %}

{% block content %}

    <section class="job-form-section job-form-section--compressed">
        <div class="container">
            <h4 class="heading">Find a <span class="accent">job </span> that will <span class="accent">fit to your experties</span></h4>
            <form id="job-main-form" method="get" action="#" class="job-main-form">
                <div class="controls">
                    <div class="row align-items-end">
                        <div class="col-sm-1 col-lg-2"></div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="profession">Position</label>
                            <input type="text" id="position" name="position"
                                   placeholder="Position you are looking for" class="form-control">
                        </div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="location">Location</label>
                            <input type="text" id="location" name="location" placeholder="Any particular location?"
                                   value="" class="form-control">
                        </div>
                        <div class="col-sm-1 col-lg-2 form-group">
                            <button type="submit" name="name"
                                    class="btn btn-outline-white-primary job-main-form__button">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ jobs.count }}</span> jobs</h3>
            {% for job in jobs %}
                <div class="job-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/itsourcecodes.jpg' %}"
                                         alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="job__title"><a
                                            href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a></h4>
                                    <p class="job__company">
                                        {{ job.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker job__location"></i>
                            {{ job.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ job.created_at|timesince }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}